foreground           #ffffff
background           #1e1e1e
selection_foreground #1e1e1e
selection_background #ff8800
cursor               #ff8800
url_color            #ff8800

window_padding_width 4
confirm_os_window_close 0

font_size 11.0

enable_audio_bell no
visual_bell_duration 0.0
