[Appearance]
color_scheme_path=/usr/share/qt5ct/colors/darker.conf
custom_palette=true
standard_dialogs=default
style=Breeze

[Fonts]
fixed="Monospace,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
general="Sans,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
